#!/usr/bin/env bash

function backup() {
    date=$(date +%Y%m%d-%H:%M)
    cd ..
    zip -rq ./vj_backup/vj_$date.zip ./vj
    echo "Finished backup"
}

function usage(){
    echo "USAGE:"
    echo "vj start|stop|info [web|judger|proxyer]"
    echo "vj backup"
    echo
    exit -1
}

case $1 in
start)
    case $2 in
    web)
        systemctl start vj_web.service
        echo "web"
    ;;
    judger)
        systemctl start vj_judger.service
        echo "judger"
    ;;
    proxyer)
        systemctl start vj_proxyer.service
        echo "proxyer"
    ;;
    *)
        systemctl start vj_web.service
        echo "web"
        systemctl start vj_judger.service
        echo "judger"
        systemctl start vj_proxyer.service
        echo "proxyer"
    ;;
esac
;;
stop)
    case $2 in
    web)
        systemctl stop vj_web.service
        echo "web"
    ;;
    judger)
        systemctl stop vj_judger.service
        echo "judger"
    ;;
    proxyer)
        systemctl stop vj_proxyer.service
        echo "proxyer"
    ;;
    *)
        systemctl stop vj_web.service
        echo "web"
        systemctl stop vj_judger.service
        echo "judger"
        systemctl stop vj_proxyer.service
        echo "proxyer"
    ;;
esac
;;
info)
    case $2 in
    web)
        systemctl status vj_web.service
    ;;
    judger)
        systemctl status vj_judger.service
    ;;
    proxyer)
        systemctl status vj_proxyer.service
    ;;
    *)
        systemctl status vj_web.service
        systemctl status vj_judger.service
        systemctl status vj_proxyer.service
    ;;
    esac
;;
backup)
    backup
;;
*)
    usage
;;
esac
