#!/usr/bin/env bash

function backup() {
    date=$(date +%Y%m%d-%H:%M)
    mongodump -h localhost:27017 -d vj -o ./dbbackup
    cd ..
    zip -rq ./vj_backup/vj_$date.zip ./vj
    echo "Finished backup"
}

function usage(){
    echo "USAGE:"
    echo "vj start|stop|restart|info [web|judger|ranker]"
    echo "vj backup"
    echo
    exit -1
}

case $1 in
start)
    case $2 in
    web)
        systemctl start vj_web.service
        echo "web"
    ;;
    judger)
        systemctl start vj_judger.service
        echo "judger"
    ;;
    ranker)
        systemctl start vj_ranker.service
        echo "ranker"
    ;;
    *)
        if [ -z $2 ]
        then
            systemctl start vj_web.service
            echo "web"
            systemctl start vj_judger.service
            echo "judger"
            systemctl start vj_ranker.service
            echo "ranker"
        else
            usage
        fi
    ;;
    esac
;;
stop)
    case $2 in
    web)
        systemctl stop vj_web.service
        echo "web"
    ;;
    judger)
        systemctl stop vj_judger.service
        echo "judger"
    ;;
    ranker)
        systemctl stop vj_ranker.service
        echo "ranker"
    ;;
    *)
        if [ -z $2 ]
        then
            systemctl stop vj_web.service
            echo "web"
            systemctl stop vj_judger.service
            echo "judger"
            systemctl stop vj_ranker.service
            echo "ranker"
        else
            usage
        fi
    ;;
    esac
;;
restart)
    case $2 in
    web)
        systemctl restart vj_web.service
        echo "web"
    ;;
    judger)
        systemctl restart vj_judger.service
        echo "judger"
    ;;
    ranker)
        systemctl restart vj_ranker.service
        echo "ranker"
    ;;
    *)
        if [ -z $2 ]
        then
            systemctl restart vj_web.service
            echo "web"
            systemctl restart vj_judger.service
            echo "judger"
            systemctl restart vj_ranker.service
            echo "ranker"
        else
            usage
        fi
    ;;
    esac
;;
info)
    case $2 in
    web)
        systemctl status vj_web.service
    ;;
    judger)
        systemctl status vj_judger.service
    ;;
    ranker)
        systemctl status vj_ranker.service
    ;;
    *)
        if [ -z $2 ]
        then
            systemctl status vj_web.service
            systemctl status vj_judger.service
            systemctl status vj_ranker.service
        else
            usage
        fi
    ;;
    esac
;;
backup)
    backup
;;
*)
    usage
;;
esac
